default: &default
  pool: 5
  adapter: postgresql
  encoding: unicode
  user: tindomondo
  password: NeverRunAlone!
  host: localhost


production:
  <<: *default
  database: tindomondo_production
development:
  <<: *default
  database: tindomondo_development
test: &test
  <<: *default
  database: tindomondo_test

cucumber:
  <<: *test


  
