# be sure to restart your server when you modify this file...
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
development:
  secret_key_base: iweroweiqroweiruqwoeiruqwoeiruqproqwiuerqpoweiruqwpeoriqwepotqwepruiroüieruqwpioer
test:
  secret_key_base: qwioruqweproiwquerpoqwierqoüweiqwpeoitqweporiuqweoüriuqwepriouqweproiqwproiqwuerpoqiweur
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
